-- Seed tasks from Wedding To-Do Lists.xlsx
-- Run in Supabase SQL Editor

DELETE FROM tasks WHERE id >= 0;

INSERT INTO tasks (title, description, category, assigned_to, responsible_party, important_contacts, status, priority, sort_order, due_date, completed_date, blocked_by, task_comments, completed_by, created_by) VALUES
  ('Finalize list', '', 'Guest List', 'both', 'Siobahn and Nick', '', 'in_progress', 'medium', 1, 'January 12', NULL, '', '[]', '', 'import'),
  ('Create homepage', '', 'Wedding Website', 'both', 'Siobahn and Nick', '', 'done', 'medium', 2, NULL, NULL, '', '[]', '', 'import'),
  ('Create schedule', '', 'Wedding Website', 'both', 'Siobahn and Nick', '', 'done', 'medium', 3, NULL, NULL, '', '[]', '', 'import'),
  ('Create accomodations page', '', 'Wedding Website', 'both', 'Siobahn and Nick', '', 'done', 'medium', 4, NULL, NULL, '', '[]', '', 'import'),
  ('Create About Us page', '', 'Wedding Website', 'both', 'Siobahn and Nick', '', 'pending', 'medium', 5, NULL, NULL, '', '[]', '', 'import'),
  ('Create Save the Dates', '', 'Save the Dates', 'siobhan', 'Siobhan', '', 'done', 'medium', 6, NULL, NULL, '', '[]', '', 'import'),
  ('Create Email list', '', 'Save the Dates', 'both', 'Siobhan and Nick', '', 'done', 'medium', 7, NULL, NULL, '', '[]', '', 'import'),
  ('Email Save the Dates', '', 'Save the Dates', 'nick', 'Nick', '', 'in_progress', 'medium', 8, NULL, NULL, '', '[]', '', 'import'),
  ('Pick up dress', '', 'Getting Dressed Prep', 'siobhan', 'Siobhan and Mom', '', 'done', 'medium', 9, NULL, NULL, '', '[]', '', 'import'),
  ('Get dress tailored', '', 'Getting Dressed Prep', 'siobhan', 'Siobhan and Mom', '', 'in_progress', 'medium', 10, NULL, NULL, '', '[]', '', 'import'),
  ('Get dance shoes (flower sneakers)', '', 'Getting Dressed Prep', 'both', 'Siobhan and Mom (and Nick)', '', 'pending', 'medium', 11, NULL, NULL, '', '[]', '', 'import'),
  ('Ask Erin to do hair', '', 'Getting Dressed Prep', 'siobhan', 'Siobhan', '', 'pending', 'medium', 12, NULL, NULL, '', '[]', '', 'import'),
  ('Get jewelry', '', 'Getting Dressed Prep', 'siobhan', 'Siobhan', '', 'pending', 'medium', 13, NULL, NULL, '', '[]', '', 'import'),
  ('Hire makeup artist', '', 'Getting Dressed Prep', 'siobhan', 'Siobhan', '', 'in_progress', 'medium', 14, NULL, NULL, '', '[]', '', 'import'),
  ('Practice hair style', '', 'Getting Dressed Prep', 'siobhan', 'Siobhan and Mom', '', 'pending', 'medium', 15, NULL, NULL, '', '[]', '', 'import'),
  ('Rent or buy a tux', '', 'Getting Dressed Prep', 'nick', 'Nick', '', 'pending', 'medium', 16, NULL, NULL, '', '[]', '', 'import'),
  ('Rent or buy shoes', '', 'Getting Dressed Prep', 'nick', 'Nick', '', 'pending', 'medium', 17, NULL, NULL, '', '[]', '', 'import'),
  ('Set groomsmen tux rentals', '', 'Getting Dressed Prep', 'nick', 'Nick', '', 'pending', 'medium', 18, NULL, NULL, '', '[]', '', 'import'),
  ('Buy wedding rings', '', 'Getting Dressed Prep', 'both', 'Siobhan and Nick', '', 'pending', 'medium', 19, NULL, NULL, '', '[]', '', 'import'),
  ('Get veil', '', 'Getting Dressed Prep', 'siobhan', 'Siobhan and Mom', '', 'pending', 'medium', 20, NULL, NULL, '', '[]', '', 'import'),
  ('Buy Wildflower socks', '', 'Getting Dressed Prep', 'nick', 'Nick', '', 'pending', 'medium', 21, NULL, NULL, '', '[]', '', 'import'),
  ('Call Saint John the Evangelist', '', 'Ceremony', 'nick', 'Nick', '', 'done', 'medium', 22, 'January 12', NULL, '', '[]', '', 'import'),
  ('Set up Pre-Cana', '', 'Ceremony', 'nick', 'Nick', '', 'pending', 'medium', 23, NULL, NULL, '', '[]', '', 'import'),
  ('Call Saint Richard''s Barnesville', '', 'Ceremony', 'nick', 'Nick', 'Fr. Robert Finlan 570-467-2315', 'pending', 'medium', 24, 'January 19', NULL, '', '[]', '', 'import'),
  ('Attend Pre-Cana', '', 'Ceremony', 'both', 'Siobhan and Nick', '', 'pending', 'medium', 25, NULL, NULL, '', '[]', '', 'import'),
  ('Ask groomsmen', '', 'Ceremony', 'nick', 'Nick', '', 'pending', 'medium', 26, NULL, NULL, '', '[]', '', 'import'),
  ('Ask bridesmaids', '', 'Ceremony', 'siobhan', 'Siobhan', '', 'done', 'medium', 27, NULL, NULL, '', '[]', '', 'import'),
  ('Ask ringbearer', '', 'Ceremony', 'nick', 'Nick', '', 'pending', 'medium', 28, NULL, NULL, '', '[]', '', 'import'),
  ('Ask flowergirl', '', 'Ceremony', 'siobhan', 'Siobhan', '', 'pending', 'medium', 29, NULL, NULL, '', '[]', '', 'import'),
  ('Choose lectors (2-3)', '', 'Ceremony', 'nick', 'Nick', '', 'pending', 'medium', 30, NULL, NULL, '', '[]', '', 'import'),
  ('Choose gift bearers (2-3)', '', 'Ceremony', 'both', 'Siobhan and Nick', '', 'pending', 'medium', 31, NULL, NULL, '', '[]', '', 'import'),
  ('Ask Analise (and Phil) to cantor', '', 'Ceremony', 'siobhan', 'Siobhan', '', 'pending', 'medium', 32, NULL, NULL, '', '[]', '', 'import'),
  ('Ask Lori Arentz to play piano', '', 'Ceremony', 'siobhan', 'Siobhan', '', 'pending', 'medium', 33, NULL, NULL, '', '[]', '', 'import'),
  ('Create Wedding booklet', '', 'Ceremony', 'siobhan', 'Siobhan', '', 'pending', 'medium', 34, NULL, NULL, '', '[]', '', 'import'),
  ('Ask booklet passers (2)', '', 'Ceremony', 'both', 'Siobhan and Nick', '', 'pending', 'medium', 35, NULL, NULL, '', '[]', '', 'import'),
  ('Schedule Mission BBQ', '', 'Reception', 'siobhan', 'Siobhan', '', 'done', 'medium', 36, NULL, NULL, '', '[]', '', 'import'),
  ('Attend Mission BBQ tasting', '', 'Reception', 'both', 'Siobhan and Nick', '', 'done', 'medium', 37, NULL, NULL, '', '[]', '', 'import'),
  ('Book food vendor', '', 'Reception', 'both', 'Siobhan and Nick', '', 'done', 'medium', 38, NULL, NULL, '', '[]', '', 'import'),
  ('Finalize table setup', '', 'Reception', 'both', 'Siobhan and Nick', '', 'pending', 'medium', 39, NULL, NULL, '', '[]', '', 'import'),
  ('Decide on signature drinks', '', 'Reception', 'both', 'Siobhan and Nick', '', 'pending', 'medium', 40, NULL, NULL, '', '[]', '', 'import'),
  ('Decide on drink package', '', 'Reception', 'both', 'Siobhan and Nick', '', 'pending', 'medium', 41, NULL, NULL, '', '[]', '', 'import'),
  ('Order mini cake', '', 'Reception', 'both', 'Siobhan and Nick', '', 'pending', 'medium', 42, NULL, NULL, '', '[]', '', 'import'),
  ('Verify and order desserts from Olivia', '', 'Reception', 'both', 'Siobhan and Nick', '', 'pending', 'medium', 43, NULL, NULL, '', '[]', '', 'import'),
  ('Order plastic water goblets', '', 'Reception', 'both', 'Siobhan, Nick, and Mom', '', 'pending', 'medium', 44, 'January 10', NULL, '', '[]', '', 'import'),
  ('Order silverware', '', 'Reception', 'both', 'Siobhan, Nick, and Mom', '', 'pending', 'medium', 45, 'January 10', NULL, '', '[]', '', 'import'),
  ('Order plates', '', 'Reception', 'both', 'Siobhan, Nick, and Mom', '', 'pending', 'medium', 46, 'January 10', NULL, '', '[]', '', 'import'),
  ('Organize and count cloth napkins', '', 'Reception', 'both', 'Siobhan, Nick, and Mom', '', 'pending', 'medium', 47, 'January 10', NULL, '', '[]', '', 'import'),
  ('Count and organize tablecloths', '', 'Reception', 'both', 'Siobhan, Nick, and Mom', '', 'pending', 'medium', 48, 'January 10', NULL, '', '[]', '', 'import'),
  ('Order drinking cups', '', 'Reception', 'both', 'Siobhan, Nick, and Mom', '', 'pending', 'medium', 49, 'January 10', NULL, '', '[]', '', 'import'),
  ('Collect vases', '', 'Reception', 'both', 'Siobhan, Nick, Mom et al', '', 'in_progress', 'medium', 50, NULL, NULL, '', '[]', '', 'import'),
  ('Available tables', '', 'Find out from venue', 'siobhan', 'Siobhan', '', 'pending', 'medium', 51, NULL, NULL, '', '[]', '', 'import'),
  ('food truck on Friday + Saturday', '', 'Find out from venue', 'siobhan', 'Siobhan', '', 'pending', 'medium', 52, NULL, NULL, '', '[]', '', 'import'),
  ('Remove sound system', '', 'Find out from venue', 'siobhan', 'Siobhan', '', 'done', 'medium', 53, NULL, NULL, '', '[]', '', 'import'),
  ('Remove lights', '', 'Find out from venue', 'siobhan', 'Siobhan', '', 'done', 'medium', 54, NULL, NULL, '', '[]', '', 'import'),
  ('Remove video projection', '', 'Find out from venue', 'siobhan', 'Siobhan', '', 'done', 'medium', 55, NULL, NULL, '', '[]', '', 'import'),
  ('Clarify drink package', '', 'Find out from venue', 'siobhan', 'Siobhan', '', 'pending', 'medium', 56, NULL, NULL, '', '[]', '', 'import'),
  ('See if food vendor can be removed', '', 'Find out from venue', 'siobhan', 'Siobhan', '', 'done', 'medium', 57, NULL, NULL, '', '[]', '', 'import'),
  ('Let venue know about Ray Coleman', '', 'Find out from venue', 'siobhan', 'Siobhan', '', 'pending', 'medium', 58, NULL, NULL, '', '[]', '', 'import'),
  ('Talk to venue about breakfast Sunday', '', 'Find out from venue', 'siobhan', 'Siobhan', '', 'pending', 'medium', 59, NULL, NULL, '', '[]', '', 'import'),
  ('Pick songs', '', 'DJ', 'both', 'Siobhan and Nick', '', 'pending', 'medium', 60, NULL, NULL, '', '[]', '', 'import'),
  ('Give DJ timeline of speeches, etc.', '', 'DJ', 'siobhan', 'Siobhan', '', 'pending', 'medium', 61, NULL, NULL, '', '[]', '', 'import'),
  ('Phonebook', '', 'DJ', 'siobhan', 'Siobhan', '', 'pending', 'medium', 62, NULL, NULL, '', '[]', '', 'import'),
  ('bridesmaid flowers', '', 'Flowers', 'siobhan', 'Siobhan and Mom', 'Aunt Marge will arrange and do on wedding day', 'pending', 'medium', 63, NULL, NULL, '', '[]', '', 'import'),
  ('2 altar flowers', '', 'Flowers', 'siobhan', 'Siobhan and Mom', '', 'pending', 'medium', 64, NULL, NULL, '', '[]', '', 'import'),
  ('flowers for vases', '', 'Flowers', 'siobhan', 'Siobhan and Mom', '', 'pending', 'medium', 65, NULL, NULL, '', '[]', '', 'import'),
  ('Game board sign', '', 'Signs', 'siobhan', 'Siobhan', '', 'pending', 'medium', 66, NULL, NULL, '', '[]', '', 'import'),
  ('Gold frame', '', 'Signs', 'both', 'Patricia', '', 'pending', 'medium', 67, NULL, NULL, '', '[]', '', 'import'),
  ('Until We Meet Again frame', '', 'Signs', 'both', 'Ready:)', '', 'done', 'medium', 68, NULL, NULL, '', '[]', '', 'import'),
  ('Pictures for Until We Meet Again', '', 'Signs', 'both', 'Siobhan and Nick', '', 'pending', 'medium', 69, NULL, NULL, '', '[]', '', 'import'),
  ('Hang pics on Until We Meet Again', '', 'Signs', 'both', 'Mom', '', 'pending', 'medium', 70, NULL, NULL, '', '[]', '', 'import'),
  ('Embroidered napkin for picnic basket', '', 'Signs', 'both', '', '', 'pending', 'medium', 71, NULL, NULL, '', '[]', '', 'import'),
  ('Bar menu', '', 'Signs', 'siobhan', 'Siobhan', '', 'pending', 'medium', 72, NULL, NULL, '', '[]', '', 'import'),
  ('Family tree sign', '', 'Signs', 'nick', 'Nick', '', 'pending', 'medium', 73, NULL, NULL, '', '[]', '', 'import'),
  ('Wedding photos from family', '', 'Signs', 'both', 'Siobhan and Nick', '', 'pending', 'medium', 74, NULL, NULL, '', '[]', '', 'import'),
  ('S''more sign', '', 'Signs', 'siobhan', 'Siobhan', '', 'pending', 'medium', 75, NULL, NULL, '', '[]', '', 'import'),
  ('S''more table', '', 'Signs', 'nick', 'Nick', '', 'pending', 'medium', 76, NULL, NULL, '', '[]', '', 'import'),
  ('Phone sign for Church', '', 'Signs', 'siobhan', 'Siobhan', '', 'pending', 'medium', 77, NULL, NULL, '', '[]', '', 'import'),
  ('Seating chart', '', 'Signs', 'nick', 'Nick', '', 'pending', 'medium', 78, NULL, NULL, '', '[]', '', 'import'),
  ('Table numbers (places)', '', 'Signs', 'nick', 'Nick', '', 'pending', 'medium', 79, NULL, NULL, '', '[]', '', 'import'),
  ('Bucket list sign', '', 'Signs', 'siobhan', 'Siobhan', '', 'pending', 'medium', 80, NULL, NULL, '', '[]', '', 'import'),
  ('Get wooden bucket', '', 'Signs', 'nick', 'Nick', '', 'pending', 'medium', 81, NULL, NULL, '', '[]', '', 'import'),
  ('QR code sign', '', 'Signs', 'nick', 'Nick', '', 'pending', 'medium', 82, NULL, NULL, '', '[]', '', 'import'),
  ('Cigar bar sign', '', 'Signs', 'nick', 'Nick', '', 'pending', 'medium', 83, NULL, NULL, '', '[]', '', 'import'),
  ('Plan a photo booth (ask Erin)', '', 'Signs', 'both', 'Siobhan and Nick', '', 'pending', 'medium', 84, NULL, NULL, '', '[]', '', 'import'),
  ('Pizza for rehearsal', '', 'Weekend', 'nick', 'Nick', '', 'pending', 'medium', 85, NULL, NULL, '', '[]', '', 'import'),
  ('Chips for rehearsal', '', 'Weekend', 'nick', 'Nick', '', 'pending', 'medium', 86, NULL, NULL, '', '[]', '', 'import'),
  ('Hot dogs, burgers, ketchup, buns, mustard, cheese', '', 'Weekend', 'nick', 'Nick', '', 'pending', 'medium', 87, NULL, NULL, '', '[]', '', 'import'),
  ('Beer, wine, water, soda for weekend', '', 'Weekend', 'nick', 'Nick', '', 'pending', 'medium', 88, NULL, NULL, '', '[]', '', 'import'),
  ('Make timeline of wedding day', '', 'Weekend', 'siobhan', 'Siobhan', '', 'in_progress', 'medium', 89, NULL, NULL, '', '[]', '', 'import'),
  ('Make schedule for Friday', '', 'Weekend', 'siobhan', 'Siobhan', '', 'pending', 'medium', 90, NULL, NULL, '', '[]', '', 'import'),
  ('Plan games / competitions', '', 'Weekend', 'both', 'Siobhan, Nick and Mom', '', 'pending', 'medium', 91, NULL, NULL, '', '[]', '', 'import'),
  ('Team names (places)', '', 'Weekend', 'both', 'Siobhan and Nick', '', 'pending', 'medium', 92, NULL, NULL, '', '[]', '', 'import'),
  ('Buy paper products for weekend', '', 'Weekend', 'nick', 'Nick', '', 'pending', 'medium', 93, NULL, NULL, '', '[]', '', 'import'),
  ('Buy bridal party gifts', '', 'Weekend', 'both', 'Siobhan and Nick', '', 'pending', 'medium', 94, NULL, NULL, '', '[]', '', 'import'),
  ('Welcome campfire mug with care package', '', 'Weekend', 'both', 'Siobhan and Nick', '', 'pending', 'medium', 95, NULL, NULL, '', '[]', '', 'import'),
  ('Make camp card logo', '', 'Weekend', 'both', 'Siobhan and Nick', '', 'pending', 'medium', 96, NULL, NULL, '', '[]', '', 'import'),
  ('Beer/Picture Canoe', '', 'Weekend', 'both', 'Siobhan and Nick', '', 'pending', 'medium', 97, NULL, NULL, '', '[]', '', 'import'),
  ('Photo timeline', '', 'Photo + Video', 'both', 'Siobhan and Nick', '', 'pending', 'medium', 98, NULL, NULL, '', '[]', '', 'import'),
  ('Video timeline', '', 'Photo + Video', 'both', 'Siobhan and Nick', '', 'pending', 'medium', 99, NULL, NULL, '', '[]', '', 'import'),
  ('Decide what types of pics + videos', '', 'Photo + Video', 'both', 'Siobhan and Nick', '', 'pending', 'medium', 100, NULL, NULL, '', '[]', '', 'import'),
  ('Make Olympic flag', '', 'Campground things', 'both', '', '', 'pending', 'medium', 101, NULL, NULL, '', '[]', '', 'import'),
  ('Make T-shirts', '', 'Campground things', 'both', '', '', 'pending', 'medium', 102, NULL, NULL, '', '[]', '', 'import'),
  ('test syrups for signature drink', '', 'Campground things', 'both', '', '', 'pending', 'medium', 103, NULL, NULL, '', '[]', '', 'import'),
  ('look into hayride', '', 'Campground things', 'both', '', '', 'pending', 'medium', 104, NULL, NULL, '', '[]', '', 'import'),
  ('look into trailer rental for transport and hay ride', '', 'Campground things', 'both', '', '', 'pending', 'medium', 105, NULL, NULL, '', '[]', '', 'import'),
  ('Cabin assignments', '', 'Campground things', 'both', '', '', 'in_progress', 'medium', 106, NULL, NULL, '', '[]', '', 'import'),
  ('Bridal shower guest list', '', 'Campground things', 'both', '', '', 'pending', 'medium', 107, NULL, NULL, '', '[]', '', 'import'),
  ('Finish registry', '', 'Campground things', 'both', '', '', 'pending', 'medium', 108, NULL, NULL, '', '[]', '', 'import'),
  ('Peel stickers off all jars', '', 'Campground things', 'both', '', '', 'pending', 'medium', 109, NULL, NULL, '', '[]', '', 'import'),
  ('Find sage green round placemats', '', 'Campground things', 'both', '', '', 'pending', 'medium', 110, NULL, NULL, '', '[]', '', 'import'),
  ('Make more napkin rings', '', 'Campground things', 'both', 'Mom', '', 'pending', 'medium', 111, NULL, NULL, '', '[]', '', 'import'),
  ('Hot glue napkins rings on to napkins', '', 'Campground things', 'both', '', '', 'pending', 'medium', 112, NULL, NULL, '', '[]', '', 'import'),
  ('Write speeches', '', 'Campground things', 'both', '', '', 'pending', 'medium', 113, NULL, NULL, '', '[]', '', 'import'),
  ('Write dad song', '', 'Campground things', 'both', '', '', 'pending', 'medium', 114, NULL, NULL, '', '[]', '', 'import'),
  ('Update aunt Marge on table decor', '', 'Campground things', 'both', '', '', 'pending', 'medium', 115, NULL, NULL, '', '[]', '', 'import'),
  ('Make mock table decor setup', '', 'Campground things', 'both', '', '', 'pending', 'medium', 116, NULL, NULL, '', '[]', '', 'import');

-- 116 tasks inserted